### ISSUE TITLE
Black text doesn't work well on dark themes.

### ISSUE THREAD

**Issue by jakschu** [xmikos/qhangups#9] opened 2015-04-18 22:09 UTC
I'm using xfce with a dark theme.
Text is barely readable:
![qhangups](https://cloud.githubusercontent.com/assets/1179537/7217384/13bcb382-e628-11e4-829a-d6e66d4e9295.png)

The contacts window does it right: white text on grey background.

**Comment by xmikos** [comment] 2015-04-26 21:43
The problem is that `QHangupsConversationWidget` uses `QWebView` (from _QtWebKit_) to be able to display HTML (simple formatting now, but even images in near future). And I didn't find a way how to force QWebView to use system-wide font settings yet.

If you want at least workaround for now, you can change font settings manually in CSS:
https://github.com/xmikos/qhangups/blob/master/qhangups/conversationwidget.py#L90

But I will try to find better solution...

**Comment by jakschu** [comment] 2015-05-21 00:43
Thanks, I set up some values in the stylesheet. Do you think this can be done automagically?
Maybe I can provide some help, although I'm not a python developer...

**Comment by xmikos** [comment] 2016-10-17 22:40
Should be fixed in new version 1.8.1 (thanks to @DonOregano)

**Closed as completed by xmikos** 2016-10-17 22:40 UTC
Labels: bug
